Github actionsでの自動ビルドとリリース
actlaboratory/PVP pull request #3
Opened 2024-01-02 11:39 UTC by guredora403

github actionsで自動ビルドとリリースがされるようにしました。actlab-autoではなく、github_actionsがリリースを行うようになります。ひとまずスナップショットバージョンだけ対応しました。正式リリースについては後日やります。
ワークフローの追加のほかに、ビルドスクリプトにも対応のための変更を加えています。

2024-01-03 01:13 UTC, yamahubuki requested changes

2024-01-03 01:13 UTC, yamahubuki commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
コミットタイムスタンプのタイムゾーンは、何に依存して決定されているのでしょうか。
コミッターの設定、リポジトリの設定などによってJSTであることが保証されないのであれば、変換は入れておいたほうが良いと思いますが、いかがでしょうか。

2024-01-03 01:13 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +  deploy:
このデプロイのプロセス、PRを開いただけで実行されないでしょうか。仮にそうなら、それは困るのですが。

2024-01-03 01:13 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +
ラボのサーバもたたきに行って、情報更新してあげてください。

2024-01-03 01:13 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +
失敗時のSlack通知はどのように実行されるのでしょうか。

2024-01-03 01:14 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +  deploy:
逆に、PRだけでもテストとビルドまでは動いてほしいです。

2024-01-03 01:38 UTC, guredora403 commented on tools/build.py
> +			pyinstaller_path = "pyinstaller.exe"
Github actionsでは、利用しているpythonのディレクトリが%pythonLocation%に入っています。automatedの時にはそこを指定して、そうではないときはパスが通っているディレクトリにしているので問題ないはずです。
参考: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#outputs-and-environment-variables

2024-01-03 01:39 UTC, guredora403 commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
逆にいうと、UTCであることも保証されていないので、返還を入れるのであればタイムゾーンの判定ロジックが新たに必要かと思います。やるなら検討が必要かと。

2024-01-03 01:45 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +  deploy:
pushとPRはイベントが別なので、PRが来ただけでは実行されません。手元で検証しました。PRには別のイベントがあるので、ビルドまでチェックするワークフローを定義することは可能です。やります。

2024-01-03 04:09 UTC, yamahubuki commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
そもそも、このタイムスタンプの文字列にタイムゾーン情報入っててないのでしょうか？
入ってないなら結構面倒です。

2024-01-03 04:09 UTC, yamahubuki commented on tools/build.py
> +			pyinstaller_path = "pyinstaller.exe"
automatedの場合はそれでよいです。
そうでない場合に、パスが通っていないバージョンのPythonを使う場合に困るということです。

2024-01-03 04:09 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +  deploy:
おねがいします。

2024-01-03 05:58 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +
スナップショットバージョンのビルドには実装しました。同じ方法でリリースにも実装できると思います。メッセージの内容が少ないのは後程修正します。incoming webhookをたたいていいます。

2024-01-03 06:04 UTC, guredora403 commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
iso8601形式で後ろに入っています。今調べた限り、datetimeはそれを認識して自動調整するようなのでこのままで問題ないかと思います。

2024-01-03 06:13 UTC, guredora403 commented on tools/build.py
> +			pyinstaller_path = "pyinstaller.exe"
まず、以前まではautomatedではない場合に、パスが通っているpythonのpyinstallerを使うようになっていたと思うので、その辺の仕様を変えるということになりますが、パスが通っていないpyinstallerを使いたいという状況がイメージできません。少なくとも%PYTHON%という環境変数はAppveyor固有のものかと思われます。私のマシンには存在しませんでした。そうすると、実行しているpythonの場所を新たに取得してくる処理が必要になってきますが、本当に必要でしょうか。

2024-01-03 06:14 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +
作業が終わったら一番最後に実装します。特性上動作確認ができないので。

2024-01-03 07:38 UTC, guredora403 commented
mergeに必要な関連作業:
- appveyorの停止
- secretに以下の内容を追加
	- SCRIPT_PASSWORD: サイトに設定しているスクリプトパスワード
	- SLACK_ALERT_WEBHOOK_URL: アラート通知用のSlack webhook URL

2024-01-03 08:22 UTC, yamahubuki commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
そうすると、後ろに入っているのがJSTでないタイムスタンプだった場合を考慮して、それをJSTに直す処理は必要ですね。

2024-01-03 08:35 UTC, guredora403 commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
なるほど、補正が必要ということですね。理解しました。修正しています。

2024-01-03 08:36 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +
この書き方、deployに失敗したら流れるのは確実かと思いますが、buildに失敗してdeployがそもそも実行されなかった場合も実行対象になっているでしょうか。ご確認だけお願いします。

2024-01-03 08:36 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +
BETA使えばテストできるかと思います。
後ほどお願いします。

2024-01-03 08:36 UTC, yamahubuki commented on tools/build.py
> +			pyinstaller_path = "pyinstaller.exe"
if分の条件を真逆に変えていたのを見落としてました。
Pythonを複数バージョン入れて、特定バージョンにパスを通し、その他をフルパス指定で使うようなユースケースを想定したときにこの書き方はよろしくない(実行するPyInsttallerのバージョンと実行中のPythonのバージョンが一致しなくなる)のですが、既存の問題点なので無視でもよいです。

2024-01-03 08:36 UTC, yamahubuki commented on tools/build.py
> +		dt = datetime.datetime.fromisoformat(os.environ["COMMIT_TIMESTAMP"])
自動で合わせてくれるのは間違いないですが、「JSTに合わせてほしい」という点はこちらが指定する必要があるはずです。

2024-01-03 08:41 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +
needsがチェーンになっていて、ビルドが失敗したらデプロイが動かない、デプロイが動かなかったらエラー通知処理が動くのように連鎖するので問題ないです。実際の動作も確認しました。

2024-01-03 11:34 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +
テストしました。以下のようなURLにリクエストを投げていますが、フォークしたリポジトリなので404が返ってきています。
https://stg.actlab.org/api/addAlphaVersion?repo_name=guredora403/PVP&commit_hash=be2d43d7cae139ef51921e68a65b7a284a180d17&version=2401.3.849&***"

2024-01-03 11:36 UTC, guredora403 commented
一通りの作業は終わったと認識しています。snapshotと正式リリースの自動ビルド、PRのチェックに対応しました。

2024-01-03 13:02 UTC, yamahubuki commented on .github/workflows/snapshot.yml
> +          python -m pip install wxpython
constantsを読みに行くのであれば、ソフトによっていろいろな依存があるので、素直にrequirementsを入れてください。

もしくは、build.pyが出しているversion.jsonあたりからとるとかできないでしょうか。
あのjson、必要に応じてキーは増やしてよいので、必要になる情報は底に入れておくとかがよいかもです。

2024-01-03 14:02 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +          python -m pip install wxpython
jobが違うせいでconstantsに反映されていないということがわかったのでここではpythonは使わないことにしました。最新のコードであれば問題ないはずです。

2024-01-03 21:43 UTC, guredora403 commented on .github/workflows/snapshot.yml
> +          python -m pip install wxpython
追加で申し訳ないですが、デプロイとビルドはジョブが違います。ジョブごとに新しいマシンが割り当てられ、新たにrepositoryをクローンしているので、環境もファイルも全く別なものになります。ですので、package.jsonを含めてビルドジョブ内で書き換えたファイルたちの変更も反映されていません。今回は、ビルドジョブにバージョン番号を吐き出させて、デプロイジョブからそれを参照するようにしています。結果的にデプロイにかかる時間は短縮されていますし、curlをたたくだけになったので可読性は上がっていると思います。

2024-01-04 03:46 UTC, guredora403 commented
Appveyorの設定ファイルを削除したので、設定は特に触らないままmergeしてしまって問題ないかと思われます。

2024-01-04 13:56 UTC, yncat approved these changes
LGTM

2024-01-04 13:57 UTC, merged

2024-01-04 13:58 UTC, yncat commented
あまりにもコミット数が多かったのでsquash mergeしました。ごめんね。